site_name: AWS Well-Architected Labs 
site_description: 'A collection of AWS Well-Architected workshops' 


# Repository 
repo_name: 'awslabs/aws-well-architected-labs' 
repo_url: 'https://github.com/awslabs/aws-well-architected-labs' 

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.' 


google_analytics:
    - 'UA-136796500-1' 
    - 'auto' 


theme:
    name: material 
    feature: 
        tabs: true 


nav: 
    - Home: index.md 
    - About: index.md 
    - Cost Optimization: 
        - Cost Optimization: 'Cost/README.md' 
        - Cost Optimization Fundamentals: 'Cost/Cost_Fundamentals/README.md' 
        - Cost and Usage Analysis: 'Cost/Cost_and_Usage_Analysis/README.md' 
    - Security: 
        - Security: 'Security/README.md' 
        - Cloudfront with S3: 'Security/100 - CloudFront with S3 Bucket Origin/README.md' 
    - Operational Excellence: 
        - 100 1 AWS Account Setup: 'Cost_Fundamentals/100_1_AWS_Account_Setup/README.md'
    - Reliability: 
        - Reailibility: 'Reliability/README.md' 
        - Testing Resiliency: 'Reliability/300 - Testing for Resiliency of EC2, RDS, and S3' 
    - Performance Efficiency: 
        - 100 1 AWS Account Setup: 'Cost_Fundamentals/100_1_AWS_Account_Setup/README.md'

 
 
