site_name: AWS Well-Architected Labs 
site_description: 'A collection of AWS Well-Architected workshops' 


# Repository 
repo_name: 'awslabs/aws-well-architected-labs' 
repo_url: 'https://github.com/awslabs/aws-well-architected-labs' 

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.' 



theme:
    name: material 
    feature: 
        tabs: true 


nav: 
    - Home: index.md 
    - About: about.md 
    - Cost Optimization: 
        - 100 1 AWS Account Setup: 'Cost_Fundamentals/100_1_AWS_Account_Setup/README.md' 
        - 100 2 Cost and Usage Governance: 'Cost_Fundamentals/100_2_Cost_and_Usage_Governance/README.md' 
        - 100 4 Cost and Usage Analysis: '100_4_Cost_and_Usage_Analysis/100_4_Cost_and_Usage_Analysis/README.md' 
        - 100 5 Cost Visualization: '100_5_Cost_Visualization/100_5_Cost_Visualization/README.md' 
        - 200 2 Cost and Usage Governance: 'Cost_Fundamentals/200_2_Cost_and_Usage_Governance/README.md' 
        - 200 3 Pricing Models: 'Cost_Fundamentals/200_3_Pricing_Models/README.md' 
        - 200 4 Cost and Usage Analysis: 'Cost_Fundamentals/200_4_Cost_and_Usage_Analysis/README.md' 
        - 200 5 Cost and Usage Visualization: 'Cost_Fundamentals/200_4_Cost_and_Usage_Visualization/README.md' 
    - Security: 
        - 100 Cost and Usage Analysis: 'Cost_Fundamentals/100_4_Cost_and_Usage_Analysis/README.md' 
        - 200 Cost and Usage Analysis: 'Cost_Fundamentals/200_4_Cost_and_Usage_Analysis/README.md' 
        - 300 Automated CUR Updates and Ingestion: 'Cost_and_Usage_Analysis/300_Automated_CUR_Updates_and_Ingestion' 
        - 300 Multi Account Access and Distribution: 'Cost_and_Usage_Analysis/300_Multi_Account_Access_and_Distribution' 
    - Operational Excellence: 
    - Reliability: 
    - Performance Efficiency: 


 
 
